---
stages:
- name: SelfAssembly
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: WrapPresent
    type: builder
    artifact_dir: ./
    build_type: shell
    script: |-
      #!/bin/bash
      # © Copyright IBM Corporation 2015.
      #
      # All rights reserved. This program and the accompanying materials
      # are made available under the terms of the Eclipse Public License v1.0
      # which accompanies this distribution, and is available at
      # http://www.eclipse.org/legal/epl-v10.html
      # Derived from dW article @ https://developer.ibm.com/bluemix/2014/02/17/deploy-drupal-application-ibm-bluemix/
      ##########
      # Colors - Lets have some fun ##
      ##########
      Green='\e[0;32m'
      Red='\e[0;31m'
      Yellow='\e[0;33m'
      Cyan='\e[0;36m'
      no_color='\e[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      #############
      echo ""
      echo -e "${cloud}${Cyan}  Let's setup Drupal for initial deployment${no_color}"
      echo -e "${tools}${Yellow}    Updating apt-get ...${no_color}"
      # sudo apt-get update > /dev/null 2>&1
      # Install jq
      echo -e "${tools}${Yellow}    Installing jq for JSON parsing support...${no_color}"
      sudo apt-get --assume-yes install jq > /dev/null 2>&1
      echo -e "${tools}${Yellow}    Installing zip/unzip...${no_color}"
      sudo apt-get --assume-yes install zip unzip > /dev/null 2>&1
      
      # Let's pull the open source code for Twilio-php SDK
      echo -e "${harpoons}${Yellow}    Updating git submodules ...${no_color}"
      git submodule update --init --recursive > /dev/null 2>&1
      
      echo -e "${harpoons}${Yellow}    Fetching Drupal Zip ...${no_color}"
      mkdir htdocs
      wget http://ftp.drupal.org/files/projects/agov-7.x-3.0-core.zip -nv -O ./bluezone/drupal.zip
      echo -e "${tools}${Yellow}    Extracting Drupal${no_color}"
      unzip -o ./bluezone/drupal.zip -d ./htdocs > /dev/null 2>&1
      
      echo -e "${tools}${Cyan}    Setting up default site folders ...${no_color}"
      mv ./bluezone/configtweaks/files ./htdocs/agov-7.x-3.0/sites/default

      echo -e "${tools}${Yellow}    Setting up best practice modules, libraries, themes  ...${no_color}"
      echo -e "${tools}${Cyan}      Installing Predis Redis Client Library ...${no_color}"
      wget https://github.com/nrk/predis/archive/v1.0.3.zip -nv -O ./bluezone/predis.zip
      unzip -o ./bluezone/predis.zip -d ./htdocs/agov-7.x-3.0/sites/all/libraries > /dev/null 2>&1

      echo -e "${tools}${Cyan}      Installing Security Review Module ...${no_color}"
      wget http://ftp.drupal.org/files/projects/security_review-7.x-1.2.zip -nv -O ./bluezone/securityreview.zip
      unzip -o ./bluezone/securityreview.zip -d ./htdocs/agov-7.x-3.0/sites/all/modules/contrib > /dev/null 2>&1

      echo -e "${tools}${Cyan}      Installing 403 Redirect Module ...${no_color}"
      wget http://ftp.drupal.org/files/projects/r4032login-7.x-1.8.zip -nv -O ./bluezone/r4032login.zip
      unzip -o ./bluezone/r4032login.zip -d ./htdocs/agov-7.x-3.0/sites/all/modules/contrib > /dev/null 2>&1
      
      echo -e "${tools}${Cyan}      Installing Redis Module ...${no_color}"
      wget http://ftp.drupal.org/files/projects/redis-7.x-3.11.zip -nv -O ./bluezone/redis.zip
      unzip -o ./bluezone/redis.zip -d ./htdocs/agov-7.x-3.0/sites/all/modules/contrib > /dev/null 2>&1

      echo -e "${tools}${Cyan}      Installing Varnish Module ...${no_color}"
      wget http://ftp.drupal.org/files/projects/varnish-7.x-1.0-beta3.zip -nv -O ./bluezone/varnish.zip
      unzip -o ./bluezone/varnish.zip -d ./htdocs/agov-7.x-3.0/sites/all/modules/contrib > /dev/null 2>&1
      
      echo -e "${tools}${Red}      Patching Varnish Module to fix theme_hook_original on port bug ...${no_color}"
      echo -e "${tools}${Yellow}      Reference: https://www.drupal.org/node/2371907#comment-9468011 ${no_color}"
      wget https://www.drupal.org/files/issues/varnish-2371907-24.patch -nv -O ./varnish-2371907-24.patch
      patch -d ./htdocs/agov-7.x-3.0/sites/all/modules/contrib/varnish < ./varnish-2371907-24.patch
      rm varnish-2371907-24.patch

      echo -e "${tools}${Cyan}    Setting up user provided modules, libraries and themes ...${no_color}"
      for f in ./bluezone/configtweaks/libraries/*; do
          if [ -d ${f} ]; then
              # Will not run if no directories are available
              echo -e "${harpoons}${Cyan}      Installing ${f} User-Provided Module ...${no_color}"
              mv $f ./htdocs/agov-7.x-3.0/sites/all/libraries
          else
              echo -e "${fail}${Cyan}      No User-Provided Modules detected...${no_color}"
          fi
      done
      
      for f in ./bluezone/configtweaks/modules/contrib/*; do
          if [ -d ${f} ]; then
              # Will not run if no directories are available
              echo -e "${harpoons}${Cyan}      Installing ${f} User-Provided Contrib Modules ...${no_color}"
              mv $f ./htdocs/agov-7.x-3.0/sites/all/modules/contrib
          else
              echo -e "${fail}${Cyan}      No User-Provided Contrib Modules detected...${no_color}"
          fi
      done

      for f in ./bluezone/configtweaks/modules/custom/*; do
          if [ -d ${f} ]; then
              # Will not run if no directories are available
              echo -e "${harpoons}${Cyan}      Installing ${f} User-Provided Custom Modules ...${no_color}"
              mv $f ./htdocs/agov-7.x-3.0/sites/all/modules/custom
          else
              echo -e "${fail}${Cyan}      No User-Provided Custom Modules detected...${no_color}"
          fi
      done
      
      for f in ./bluezone/configtweaks/themes/*; do
          if [ -d ${f} ]; then
              # Will not run if no directories are available
              echo -e "${harpoons}${Cyan}      Installing ${f} User-Provided Themes ...${no_color}"
              mv $f ./htdocs/agov-7.x-3.0/sites/all/themes
          else
              echo -e "${fail}${Cyan}      No User-Provided Themes detected...${no_color}"
          fi
      done

      # Organize the artifact structure to be CF PHP Buildpack friendly
      echo -e "${cloud}${Yellow}    Making artifacts CF PHP friendly ...${no_color}"
      mv ./bluezone/configtweaks/.bp-config .
      mkdir .extensions
      mv ./bluezone/configtweaks/.php-extensions .
      
      # Organize the artifact structure to facilitate BMX deploy
      echo -e "${cloud}${Yellow}    Making drupal artifacts ${Cyan}Bluemix ${Yellow}friendly ...${no_color}"
      mv ./bluezone/configtweaks/.user.ini ./htdocs/agov-7.x-3.0

      echo -e "${cloud}${Yellow}    Hardening drupal .htaccess ...${no_color}"
      echo -e "" >> ./htdocs/agov-7.x-3.0/.htaccess
      echo -e "# Forces a redirect to SSL" >> ./htdocs/agov-7.x-3.0/.htaccess
      echo -e "RewriteCond %{HTTPS} off" >> ./htdocs/agov-7.x-3.0/.htaccess
      echo -e "RewriteCond %{HTTP:X-Forwarded-Proto} !https" >> ./htdocs/agov-7.x-3.0/.htaccess
      echo -e "RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]" >> ./htdocs/agov-7.x-3.0/.htaccess
      

      # mv ./bluezone/configtweaks/.htaccess ./htdocs/agov-7.x-3.0
      #
      # Embed config file if provided
      if [ -f "./bluezone/configtweaks/settings.php" ]; then
         echo -e "${tools}${Cyan}    Drupal Config file detected ...${no_color}"
         mv ./bluezone/configtweaks/settings.php ./htdocs/agov-7.x-3.0/sites/default
      else
         echo -e "${tools}${Cyan}    NO Drupal Config file detected, using default ...${no_color}"
         cp ./htdocs/agov-7.x-3.0/sites/default/default.settings.php ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$application = getenv(\"VCAP_APPLICATION\");" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$application_json = json_decode(\$application,true);" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "if (isset(\$application_json[\"application_uris\"])) {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "  \$base_url = \"https://\" . \$application_json[\"application_uris\"][0];" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "}" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$services = getenv(\"VCAP_SERVICES\");" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$services_json = json_decode(\$services,true);" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "if (isset(\$services_json)) {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "  if (isset(\$services_json[\"user-provided\"])) {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "     foreach(\$services_json[\"user-provided\"] as \$item) {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "       if (\$item[\"name\"] == \"drupaldb\") {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "         \$postgres_config = \$item[\"credentials\"];" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "         list(\$hostname, \$port) = explode(':', \$postgres_config[\"public_hostname\"]);" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "         \$dbname = 'compose';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "       } elseif (\$item[\"name\"] == \"drupalredis\") {" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "         \$redis_config = \$item[\"credentials\"];" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "         list(\$rhostname, \$rport) = explode(':', \$redis_config[\"public_hostname\"]);" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "       }" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "     }" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "   }" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "}" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$databases = array (" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "  'default' =>" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "  array (" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "    'default' =>" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "    array (" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'driver' => 'pgsql'," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'database' => \$dbname," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'username' => \$postgres_config[\"username\"]," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'password' => \$postgres_config[\"password\"]," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'host' => \$hostname," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'port' => \$port," >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "      'prefix' => 'main_'" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "    )" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "  )" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e ");" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
      
         # Useful only if Redis Caching is desired
         # Reference: http://dropbucket.org/node/242
         # Reference: https://redislabs.com/drupal-redis
         echo -e "/*" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "// Setup Redis Cache for Drupal if service is available" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "define('PREDIS_BASE_PATH', DRUPAL_ROOT . '/sites/all/libraries/predis-1.0.3/');" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['redis_client_interface'] = 'Predis';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['redis_client_host'] = \$rhostname;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['redis_client_port'] = \$rport;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['redis_client_password'] = \$redis_config[\"password\"];" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['lock_inc'] = 'sites/all/modules/contrib/redis/redis.lock.inc';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_backends'][] = 'sites/all/modules/contrib/redis/redis.autoload.inc';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_default_class'] = 'Redis_Cache';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php 
         echo -e "*/" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
      
         echo -e "" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "//Tell Drupal it is behind a proxy" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['reverse_proxy'] = TRUE;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_backends'][] = 'sites/all/modules/contrib/varnish/varnish.cache.inc';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "// Tell Drupal what addresses the proxy server(s) use." >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['reverse_proxy_addresses'] = array('127.0.0.1');" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['page_cache_invoke_hooks'] = FALSE;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache'] = 1;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_lifetime'] = 0;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['page_cache_maximum_age'] = 600;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_class_cache_form'] = 'DrupalDatabaseCache';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['cache_class_cache_page'] = 'DrupalDatabaseCache';" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php 
         echo -e "\$conf['omit_vary_cookie'] = true;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "drupal_fast_404();" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['drupal_http_request_fails'] = FALSE;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
         echo -e "\$conf['allow_authorize_operations'] = FALSE;" >> ./htdocs/agov-7.x-3.0/sites/default/settings.php
      fi
      
      # Cleaning up
      echo -e "${litter}${Yellow}    Cleaning up repository...${no_color}"
      rm -rf ./bluezone
      rm -rf .bluemix
      
      # Generate Config Fetcher Script
      IFS='|' read -ra PROJECT_NAME <<< "$IDS_PROJECT_NAME"
      echo -e "${tools}${Yellow}    Generating config helper download script...${no_color}"
      echo -e "#!/bin/bash" > fetchConfig.sh
      echo -e "rm ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      echo -e "cf files${PROJECT_NAME[1]} /app/htdocs/agov-7.x-3.0/sites/default/settings.php > ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      echo -e "sed -i -e '1,3d' ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      chmod +x fetchConfig.sh
      echo -e "${present} ${beers}${Green}  Way to go! Your Drupal Assembly present is ready!"
- name: SameDayDelivery
  inputs:
  - type: job
    stage: SelfAssembly
    job: WrapPresent
  triggers:
  - type: stage
  jobs:
  - name: OpenPresent
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      # © Copyright IBM Corporation 2015.
      #
      # All rights reserved. This program and the accompanying materials
      # are made available under the terms of the Eclipse Public License v1.0
      # which accompanies this distribution, and is available at
      # http://www.eclipse.org/legal/epl-v10.html
      # For some reason, the deploy stage shell has tracing turned on.  Lets turn it off
      set +x
      ##########
      # Colors - Lets have some fun ##
      ##########
      Green='\e[0;32m'
      Red='\e[0;31m'
      Yellow='\e[0;33m'
      Cyan='\e[0;36m'
      no_color='\e[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      #############
      # http://serverfault.com/questions/7503/how-to-determine-if-a-bash-variable-is-empty#answer-382740
      if [ -z $(cf s|grep drupaldb|cut -d" " -f1-1) ]; then
        echo -e "${fail}${Red}  PostGresql Service Instance [${Yellow}drupaldb${Red}] was not found${no_color}"
        return 1
      fi
      
      if [ -z $(cf s|grep drupalredis|cut -d" " -f1-1) ]; then
        echo -e "${fail}${Red}  Redis Service Instance [${Yellow}drupalredis${Red}] was not found${no_color}"
      fi

      echo -e "${tools}${Yellow}  Sendgrid detection routine ...${no_color}" > /dev/null 2>&1
      if [ -n $(cf s|grep sendgrid|cut -d" " -f1-1) ] && [ $(cf s|grep sendgrid|cut -d" " -f1-1) != "sendmail" ]; then
        echo -e "${eyes}${Yellow}   Detected existing sendgrid service ${existingSendgrid} within target space${no_color}"
        echo -e "${tools}${Yellow}    Updating manifest.yml file to match target space sendgrid service${no_color}"
        sed -e "s/sendmail/$(cf s|grep sendgrid|cut -d" " -f1-1)/g" ./manifest.yml > manifest.new
        rm manifest.yml
        mv manifest.new manifest.yml
      else
        echo -e "${fail}${Red}    Sendgrid Service ${Yellow}sendmail${Red} was not available${no_color}"
      fi

      p=0
      until [ $p -ge 2 ]
      do
         cf push "${CF_APP}" && echo -e "${beer} ${beers}${Green}  Congrats! Your secure Drupal deploy is up and running!${no_color}" && echo -e "${beer} ${beers}${Green}  finis coronat opus${no_color}" && break
         p=$[$p+1]
         sleep 10
      done
      # view logs
      #cf logs "${CF_APP}" --recent
